apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260506-145111-89rhwdve9ajk-service
spec:
  selector:
    app: enterprise-system-20260506-145111-89rhwdve9ajk
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
